### ISSUE TITLE
on combining reducers

### ISSUE THREAD

**Issue by mckennatim** [ryardley/rxflux#1]
Ok so at the heart of things:

```
action$.scan(reducer).subscribe(renderer) 
```

is cool. How might one combine reducers? I've been thinking I would need to do some kind of merge ala:    

```
var state = Rx.Observable.merge(
  increase,
  decrease,
  input
).scan((state, changeFn) => changeFn(state), {
  count: 0,
  inputValue: ''
});
```

(from http://reactivex.io/rxjs/manual/tutorial.html#state-stores) 
but I can't quite wrap my head around it

**Comment by ryardley** [comment]
You don't need to combine reducers using Rx. You could just write a function that works in a similar way to redux. 

``` ja
function combineReducers(reducersObject) {
  const keys = Object.keys(reducersObject);
  return (state = {}, action) => keys.reduce((currState, key) => {
    const reducer = reducersObject[key];
    return {
      ...currState,
      [key]: reducer(currState[key], action)
    };
  }, state);
}


```
